### ISSUE TITLE
Last frame missing 

### ISSUE THREAD

**Issue by Kayani11** [phoboslab/jsmpeg#51]
While decoding the raw mpeg1 video on the client side. The last frame is always missing. Actually its buffered by the code at Javascript and displayed when you send a new frame from server. Is this how the algorithm works or is there some kind of issue with the code which can be resolved.

**Comment by phoboslab** [comment]
Since jsmpeg only deals with raw mpeg1video (elementary) streams, we have no other way to find if we have enough data to decode a full picture, other than waiting for the start code of the next frame. Only when we have received the start code for the next frame, we can be certain that the data for the previous frame is complete and we can decode it.

Why is this one frame lag a problem for your use case?

**Comment by Kayani11** [comment]
Actually we are trying live streaming of our desktop app so one frame lag creates an issue

**Comment by phoboslab** [comment]
Should be fixed in current version.

**Comment by ygnn123** [comment]
Hi. Now I try to use your api for my project, and decoding of all frames is critical feature for me. But now I recive only 299 frames instead 300. (((

Does this bug not fixed?
