### ISSUE TITLE
Seeking / Scrubbing

### ISSUE THREAD

**Issue by addroid** [phoboslab/jsmpeg#9]
I'm attempting to add a seek function to this. I've been attempting to manipulate the buffer index to seek, but haven't had much luck. Not sure I'm fully wrapping my head around the frame decoding aspect of the BitArray. Any chance you'll be adding a seek function? Preferably to a given time in the video?

**Comment by shanytc** [comment]
I wasn't able to see to a specific Frame, i've tried the code above, however the PICTURE_TYPE_I returns only intra ? key frames, not ALL frames... any luck on having a function which can see to a specific frame?

**Comment by andyearnshaw** [comment]
@shanytc all non-intra frames rely on the previous frame being decoded first, a key factor in compression. If you want to seek to a specific frame, you'd first have to decode the intra frame before it, then all the frames following, skipping drawing until you get to the desired frame.

I wouldn't recommend doing this, however, as it could potentially take a long time to decode all those frames.

**Comment by shanytc** [comment]
@andyearnshaw
Does it mean that if I want to go to frame 54 for example,
I have to scan all Intra keys to the one most closes to 54 (say instra is 39 sicne the next one is 58) and then loop 15 times (54-39) the function findNextMPEGStartCode() just to be on frame 54? and then update call decodePicture() to display it?

maybe @phoboslab can shed some light?

I basically want to attach a seek bar to the jsmpeg decoded file and scrub through the video back and forward in real time.


Other option I've had in mind is to loop all frames with findNextMPEGStartCode() and decodePicture() (do i still need to check for intra frames here?) it and then dump the image from the canvas, and then store that image into an array of images so i can scrub through all images instead of the mpeg itself...

**Comment by phoboslab** [comment]
Modern encoders usually include one intra frame about every 30 frames (or once per second). So if you control the encoding step, you can make sure your videos include these intra frames. This would probably be good enough to implement a seekbar, depending on your use case. Many videohosters and their flash players only allow you to jump to intra frames as well.

Otherwise, yes, you have to jump to the closest intra frame and decode(!) all frames in between this intra frame and your jump target. The decoding is necessary, because all frames following an intra frame only encoded changed based on the previous frame and rely on the decoded YCrCb buffers.

jsmpeg includes an option to skip the final YCrCb to RGB conversion when decoding, which speeds things up a bit: `this.decodePicture(DECODE_SKIP_OUTPUT);`


Your other solution, storing decoded frames, would need a lot of time to initially decode all frames and a lot of RAM to keep those images in memory. That's probably not feasible for videos longer than a few seconds.

**Comment by shanytc** [comment]
@phoboslab I will try to work on it! But it would be nice if you can (because you coded this awesome library) also include an option to seek a frame?

**Comment by phoboslab** [comment]
Looking into right now!

**Comment by shanytc** [comment]
@phoboslab THANK YOU!!!!!

**Comment by phoboslab** [comment]
```
// If you pass 'seekable: true' in the options, you can seek to a specific frame
// or time in the video.

var player = new jsmpeg('file.mpeg', {canvas: canvas, seekable: true});

player.seekToFrame(1200); // Seek to intra frame before frame 1200
player.seekToTime(20); // Seek to intra frame before 20sec

// seekToFrame() and seekToTime() only seek to the closest, previous intra frame by
// default. If you want to seek to the exact frame or time, pass 'true' as second
// parameter.
// Depending on the input video, this can be potentially slow, as jsmpeg has
// to decode all frames between the previous intra frame and the seek target

player.seekToFrame(1200, true); // Seek to frame 1200 exactly
```

**Comment by shanytc** [comment]
@phoboslab thanks for the update!!! it works perfectly!

Last question, When using the seekToFrame(frame, true);
I get duplicated frames when ever reaching an index

for example, if index is 15
and seeking to 15, seeking to 16 will still show 15. that happens only when reaching intra frames.

Wondering if you can look it up?

**Comment by shanytc** [comment]
@phoboslab 
Awesome update! it works awesome!!
I noticed thought that, when seeking to some frame towards the END of a movie and then seek to the next frame (using the same function), it won't display the right image.but when i hit PLAY, it WILL play the right frames after.

example:
total frames: 560
seek to frame: 555 (show an image)
seek to frame: 556 (shows same image)
but when hit play from frame 555, it will show the images just fine.

**Comment by phoboslab** [comment]
You're right! The above commit should fix this. Thanks!

**Comment by dttraffic** [comment]
@phoboslab yes, that -1 removal indeed fixes that (in the beginning of a video), though i am still getting duplicated frames when seeking in mid video.. wonder why.. 

As for the end of the movie frames bug, did you manage to check it out? the play() function indeed plays through all the frames, but seeking to the few frames towards the end and then seeking to the next frame after will not display the next frame.

**Comment by shanytc** [comment]
@phoboslab yes, that -1 removal indeed fixes that (in the beginning of a video), though i am still getting duplicated frames when seeking in mid video.. wonder why..

As for the end of the movie frames bug, did you manage to check it out? the play() function indeed plays through all the frames, but seeking to the few frames towards the end and then seeking to the next frame after will not display the next frame.

**Comment by phoboslab** [comment]
You're passing `true` to the seek function, to indicate exact seeking, right? I.e.:
```javascript
player.seekToFrame(1234, true);
```

Do you have a test case? I can't seem to reproduce this with the Big Buck Bunny video.

**Comment by shanytc** [comment]
@phoboslab i am using this file for testing

https://dl.dropboxusercontent.com/u/3038723/movie.mpg

and yes, i am using TRUE in the seekToFrame() function

**Comment by phoboslab** [comment]
So, I noticed you can't seek to or past the last intra frame in the file. Thanks again :)

**Comment by shanytc** [comment]
@phoboslab Yeah this works awesome!!!! Just checked it out ;)

As for the duplicated frames (intra shows twice?) what do you think?

**Comment by phoboslab** [comment]
Looks like a frame rate conversion issue. Frame 37 & 38 and 61 & 62 are the same as well. Thats one dup every 25 frames - the framerate of the mpeg is 23.98 so I assume the source video was 25fps.

Just encode the mpeg with 25fps as well:
```
ffmpeg -i movie.mp4 -r 25 movie.mpg
```

**Comment by shanytc** [comment]
Ok great, I suspected it might be a frame rate issue, just wanted to make sure. Thanks @phoboslab you're awesome!
